apiVersion: v1
kind: Service
metadata:
  name: athena-backend
  namespace: athena
  labels:
    app: athena-backend
spec:
  type: ClusterIP
  selector:
    app: athena-backend
  ports:
    - name: http
      port: 8000
      targetPort: 8000
